name: GitHub Actions

on:
  pull_request:
     branches-ignore:
       - '*no-ci*'
  push:
    tags:
      - "*"
    branches:
      - master
      - "release*"

env:
  PYANSYS_OFF_SCREEN: True
  DPF_PORT: 32772

jobs:
  test_windows:
    name: Windows
    runs-on: windows-2019

    env:
      ANSYS_VERSION: 221
      AWP_ROOT221: ./dpf-standalone/v221

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8

      - name: Clone dpf-standalone
        run: |
          git clone https://${{secrets.DPF_PIPELINE}}@github.com/ansys-dpf/dpf-standalone

      - name: Set SERVER
        run: echo "SERVER=$env:AWP_ROOT221"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Extract standalone zip
        run: |
          ls
          cd dpf-standalone
          7z x v221.7z
          ls v221

      - name: Install ansys-dpf-core
        shell: cmd
        run: |
          pip install -r requirements_build.txt
          python setup.py bdist_wheel
          FOR /F %%a in ('dir /s/b dist\*.whl') do SET WHEELPATH=%%a
          ECHO %WHEELPATH%
          cd tests
          pip install %WHEELPATH%
          python -c "from ansys.dpf import core; print(core.Report(gpu=False))"

      - name: Start DPF Server
        run: |
          cd $env:SERVER\aisol\bin\winx64
          ls .
          Start-Process -FilePath "./Ans.Dpf.Grpc.bat" -ArgumentList "--address 127.0.0.1 --port $env:DPF_PORT" -RedirectStandardOutput "log.txt"
          python -c "from ansys.dpf import core; core.connect_to_server(port=$env:DPF_PORT); print('Python Connected')"
        timeout-minutes: 1

      - name: Kill all servers
        shell: cmd
        run: |
          tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
          ECHO %ERRORLEVEL%
          if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)
        continue-on-error: true

      - name: Show DPF Server Logs
        run: Get-Content -Path $env:SERVER\aisol\bin\winx64\log.txt
        continue-on-error: true
        if: always()

      - name: WHEEL publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ansys_dpf_core_wheel
          path: /dist/*


      - name: Install Test Environment
        run: |
          pip install -r requirements_test.txt
        if: always()

      - name: Test API Docstrings
        run: |
           pytest --doctest-modules --junitxml=junit/test-doctests-results.xml ansys/dpf/core
        if: always()

      - name: Publish Doc Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: junit/test-doctests-results.xml

      - name: Remove local copy of ansys-dpf-core
        shell: cmd
        run: |
          @echo on
          cd $(System.DefaultWorkingDirectory)
          rmdir /s /q .\ansys\
        if: always()

      - name: Test Core API
        run: |
           cd tests
           pytest -v --junitxml=junit/test-results.xml --reruns 2 .
        if: always()