name: GitHub Actions

on:
  pull_request:
     branches-ignore:
       - '*no-ci*'
  push:
    tags:
      - "*"
    branches:
      - master
      - "release*"

env:
  PYANSYS_OFF_SCREEN: True
  DPF_PORT: 32772

jobs:
  test_windows:
    name: Windows
    runs-on: windows-2019

    env:
      ANSYS_VERSION: 221

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8

      - name: Clone dpf-standalone
        run: |
          git clone https://${{secrets.DPF_PIPELINE}}@github.com/ansys-dpf/dpf-standalone

      - name: Set AWP_ROOT$(ANSYS_VERSION)
        run: echo "AWP_ROOT$env:ANSYS_VERSION=$(echo ${{github.workspace}}/dpf-standalone/v221 | cut -c 1-6)" >> $GITHUB_ENV

      - name: Set SERVER
        run: echo "SERVER=$(echo $env:AWP_ROOT($env:ANSYS_VERSION) | cut -c 1-6)" >> $GITHUB_ENV

      - name: Extract some files
        run: |
          ls
          7z x dpf-standalone/v221.7z
          ls dpf-standalone/

      - name: Install ansys-dpf-core
        shell: cmd
        run: |
          pip install -r requirements_build.txt
          python setup.py bdist_wheel
          FOR /F %%a in ('dir /s/b dist\*.whl') do SET WHEELPATH=%%a
          ECHO %WHEELPATH%
          cd tests
          pip install %WHEELPATH%
          python -c "from ansys.dpf import core; print(core.Report(gpu=False))"

      - name: Start DPF Server
        run: |
          cd $env:SERVER
          ls $env:SERVER\aisol\bin\winx64
          echo $env:SERVER
          START /B Ans.Dpf.Grpc.bat --address 127.0.0.1 --port %DPF_PORT% > log.txt 2>&1
          python -c "from ansys.dpf import core; core.connect_to_server(port=$(DPF_PORT)); print('Python Connected')"
        timeout-minutes: 1

      - name: WHEEL publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ansys_dpf_core_wheel
          path: /dist/*

      - name: Kill all servers
        shell: cmd
        run: |
          tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
          ECHO %ERRORLEVEL%
          if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)

      - name: Install Test Environment
        run: |
          pip install -r requirements_test.txt

      - name: Test API Docstrings
        run: |
           pytest --doctest-modules --junitxml=junit/test-doctests-results.xml ansys/dpf/core

      - name: Publish Doc Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: junit/test-doctests-results.xml

      - name: Remove local copy of ansys-dpf-core
        shell: cmd
        run: |
          @echo on
          cd $(System.DefaultWorkingDirectory)
          rmdir /s /q .\ansys\