name: GitHub Actions

on:
  pull_request:
     branches-ignore:
       - '*no-ci*'
  push:
    tags:
      - "*"
    branches:
      - master
      - "release*"

env:
  python.version: '3.8'
  PYANSYS_OFF_SCREEN: True
  DPF_PORT: 32772
  ANSYS_VERSION: 221
  AWP_ROOT221: ""

jobs:
  Windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2


    - name: Setup Python
      uses: actions/setup-python@v2.1.4
      with:
        python-version: 3.8

    - name: Install ansys-dpf-core
      run: |
        pip install -r requirements_build.txt
        python setup.py bdist_wheel
        FOR /F %%a in ('dir /s/b dist\*.whl') do SET WHEELPATH=%%a
        ECHO %WHEELPATH%
        pip install %WHEELPATH%
        python -c "from ansys.dpf import core; print(core.Report(gpu=False))"
