name: GitHub Actions

on:
  pull_request:
     branches-ignore:
       - '*no-ci*'
  push:
    tags:
      - "*"
    branches:
      - master
      - "release*"

env:
  PYANSYS_OFF_SCREEN: True
  DPF_PORT: 32772

jobs:
  test_windows:
    name: Windows
    runs-on: windows-2019

    env:
      ANSYS_VERSION: 221

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8

      - name: Clone dpf-standalone
        run: |
          git clone https://${{secrets.DPF_PIPELINE}}@github.com/ansys-dpf/dpf-standalone

      - name: Set AWP_ROOT$env:ANSYS_VERSION
        run: echo "AWP_ROOT$env:ANSYS_VERSION=${{github.workspace}}\dpf-standalone/v221"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Set SERVER
        run: echo "SERVER=$env:AWP_ROOT221"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Extract standalone zip
        run: |
          ls
          cd dpf-standalone
          7z x v221.7z
          ls v221

      - name: Install ansys-dpf-core
        shell: cmd
        run: |
          pip install -r requirements_build.txt
          python setup.py bdist_wheel
          FOR /F %%a in ('dir /s/b dist\*.whl') do SET WHEELPATH=%%a
          ECHO %WHEELPATH%
          cd tests
          pip install %WHEELPATH%
          python -c "from ansys.dpf import core; print(core.Report(gpu=False))"

      - name: Start DPF Server
        run: |
          cd $env:SERVER\aisol\bin\winx64
          ls .
          Start-Process -FilePath "./Ans.Dpf.Grpc.bat" -ArgumentList "--address 127.0.0.1 --port $env:DPF_PORT" -RedirectStandardOutput "log.txt"
          python -c "from ansys.dpf import core; core.connect_to_server(port=$env:DPF_PORT); print('Python Connected')"
        timeout-minutes: 1

      - name: Kill all servers
        shell: cmd
        run: |
          tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
          ECHO %ERRORLEVEL%
          if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)
        continue-on-error: true

      - name: Show DPF Server Logs
        run: Get-Content -Path $env:SERVER\aisol\bin\winx64\log.txt
        continue-on-error: true
        if: always()

      - name: WHEEL publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ansys_dpf_core_wheel
          path: ./dist/*

      - name: Install OpenGL
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = "Stop"
          $PSDefaultParameterValues['*:ErrorAction']='Stop'
          git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
          powershell gl-ci-helpers/appveyor/install_opengl.ps1

      - name: Install test offscreen rendering
        run: |
          .ci/setup_headless_display.sh
          pip install -r .ci/requirements_test_xvfb.txt
          python .ci/display_test.py

      - name: Install Test Environment
        run: |
          pip install -r requirements_test.txt
        if: always()

      - name: Test API Docstrings
        run: |
           pytest --doctest-modules --junitxml=junit/test-doctests-results.xml ansys/dpf/core

      - name: Kill all servers
        shell: cmd
        run: |
          tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
          ECHO %ERRORLEVEL%
          if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)
        continue-on-error: true

      - name: Publish Doc Test Results
        uses: actions/upload-artifact@v2
        with:
          name: ansys_dpf_core_doctest
          path: junit/test-doctests-results.xml
        if: always()

      - name: Remove local copy of ansys-dpf-core
        run: Remove-Item ".\ansys\" -Recurse
        if: always()

      - name: Test Core API
        run: |
          cd tests
          $files = Get-ChildItem -Path test_*
          $split_num = $files.Count / 2
          for ($i=0; $i -lt $split_num; $i++) {
            $outfile = $files[$i].Name
            $newfile = "a"+$outfile
            Rename-Item -Path $outfile -NewName $newfile
          }
          ls .
          pytest -v --junitxml=junit/test-resultsa.xml --reruns 2 .
          $new_files = Get-ChildItem -Path atest_*

          for ($i=0; $i -lt $split_num; $i++) {
            Rename-Item -Path $new_files[$i].FullName -NewName $files[$i].FullName
          }
          pytest -v --junitxml=junit/test-resultsb.xml --reruns 2 .

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: ansys_dpf_core_pytest
          path: junit/test-results*.xml
        if: always()

      - name: Kill all servers
        shell: cmd
        run: |
          tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
          ECHO %ERRORLEVEL%
          if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)
        continue-on-error: true

  build_doc:
    name: Documentation
    runs-on: windows-2019

    env:
      ANSYS_VERSION: 221

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8

      - name: Clone dpf-standalone
        run: |
          git clone https://${{secrets.DPF_PIPELINE}}@github.com/ansys-dpf/dpf-standalone

      - name: Set AWP_ROOT$env:ANSYS_VERSION
        run: echo "AWP_ROOT$env:ANSYS_VERSION=${{github.workspace}}\dpf-standalone/v221"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Set SERVER
        run: echo "SERVER=$env:AWP_ROOT221"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Extract standalone zip
        run: |
          ls
          cd dpf-standalone
          7z x v221.7z
          ls v221

      - name: Install ansys-dpf-core
        shell: cmd
        run: |
          pip install -r requirements_build.txt
          python setup.py bdist_wheel
          FOR /F %%a in ('dir /s/b dist\*.whl') do SET WHEELPATH=%%a
          ECHO %WHEELPATH%
          cd tests
          pip install %WHEELPATH%
          python -c "from ansys.dpf import core; print(core.Report(gpu=False))"

      - name: Start DPF Server
        run: |
          cd $env:SERVER\aisol\bin\winx64
          ls .
          Start-Process -FilePath "./Ans.Dpf.Grpc.bat" -ArgumentList "--address 127.0.0.1 --port $env:DPF_PORT" -RedirectStandardOutput "log.txt"
          python -c "from ansys.dpf import core; core.connect_to_server(port=$env:DPF_PORT); print('Python Connected')"
        timeout-minutes: 1

      - name: Kill all servers
        shell: cmd
        run: |
          tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
          ECHO %ERRORLEVEL%
          if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)
        continue-on-error: true

      - name: Show DPF Server Logs
        run: Get-Content -Path $env:SERVER\aisol\bin\winx64\log.txt
        continue-on-error: true
        if: always()

      - name: Install OpenGL
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = "Stop"
          $PSDefaultParameterValues['*:ErrorAction']='Stop'
          git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
          powershell gl-ci-helpers/appveyor/install_opengl.ps1

      - name: Install test offscreen rendering
        run: |
          .ci/setup_headless_display.sh
          pip install -r .ci/requirements_test_xvfb.txt
          python .ci/display_test.py

      - name: Install documentation packages for Python
        run: |
          pip install -r requirements_docs.txt

      - name: Build Documentation
        id: build_doc_task
        shell: cmd
        continue-on-error: true
        run: |
          cd .ci
          build_doc.bat

      - name: ReBuild Documentation
        shell: cmd
        if: steps.main.build_doc_task.result=='failure'
        run: |
          cd docs/
          call make html

      - name: DOCUMENTATION zip artifacts
        run: |
          7z a -tzip ./docs/archive/doc-ansys-dpf-core.zip ./docs/build
        if: always()

      - name: Kill all servers
        shell: cmd
        run: |
          tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
          ECHO %ERRORLEVEL%
          if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)
        continue-on-error: true
        if: always()

      - name: Publish Doc Test Results
        uses: actions/upload-artifact@v2
        with:
          name: doc-ansys-dpf-core
          path: ./docs/archive/doc-ansys-dpf-core.zip
        if: always()

      - name: Publish Documentation artifact
        uses: actions/upload-artifact@v2
        with:
          name: doc-ansys-dpf-core
          path: junit/test-results.xml
        if: always()
