name: GitHub Actions

on:
  pull_request:
     branches-ignore:
       - '*no-ci*'
  push:
    tags:
      - "*"
    branches:
      - master
      - "release*"

env:
  PYANSYS_OFF_SCREEN: True
  DPF_PORT: 32772

jobs:
  test_windows:
    name: Windows
    runs-on: windows-2019

    env:
      ANSYS_VERSION: 221

    steps:
      - uses: actions/checkout@v2
      - uses: actions/prepare-windows-env-action@v1
        with:
          version-number: $env:ANSYS_VERSION

      - name: WHEEL publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ansys_dpf_core_wheel
          path: ./dist/*

      - name: Install Test Environment
        run: |
          pip install -r requirements_test.txt
        if: always()

      - name: Test API Docstrings
        run: |
           pytest --doctest-modules --junitxml=junit/test-doctests-results.xml ansys/dpf/core
        if: always()

      - name: Kill all servers
        shell: cmd
        run: |
          tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
          ECHO %ERRORLEVEL%
          if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)
        continue-on-error: true

      - name: Publish Doc Test Results
        uses: actions/upload-artifact@v2
          with:
            name: ansys_dpf_core_pytest
            path: junit/test-doctests-results.xml
        if: always()

      - name: Remove local copy of ansys-dpf-core
        run: Remove-Item ".\ansys\" -Recurse
        if: always()

      - name: Test Core API
        run: |
           cd tests
           pytest -v --junitxml=junit/test-results.xml --reruns 2 .
        if: always()

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
          with:
            name: ansys_dpf_core_pytest
            path: junit/test-results.xml
        if: always()

      - name: Run example scripts
        run: python .ci/run_examples.py
        if: always()
